=== gabriela-n/XML2025_project_37_8MI0600303_855305/fortresses.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    
    <!-- Корен елемент -->
    <xs:element name="catalog">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="regions" type="RegionsType"/>
                <xs:element name="areas" type="AreasType"/>
                <xs:element name="fortresses" type="FortressesType"/>
            </xs:sequence>
        </xs:complexType>
        
        <!-- Ключове и референции -->
        <xs:key name="regionKey">
            <xs:selector xpath="regions/region"/>
            <xs:field xpath="@id"/>
        </xs:key>
        
        <xs:key name="areaKey">
            <xs:selector xpath="areas/area"/>
            <xs:field xpath="@id"/>
        </xs:key>
        
        <xs:keyref name="areaRegionRef" refer="regionKey">
            <xs:selector xpath="areas/area"/>
            <xs:field xpath="@regionRef"/>
        </xs:keyref>
        
        <xs:keyref name="fortressAreaRef" refer="areaKey">
            <xs:selector xpath="fortresses/fortress/location"/>
            <xs:field xpath="areaRef"/>
        </xs:keyref>
        
        <xs:key name="fortressKey">
            <xs:selector xpath="fortresses/fortress"/>
            <xs:field xpath="@id"/>
        </xs:key>
    </xs:element>
    
    <!-- Тип за колекция от региони -->
    <xs:complexType name="RegionsType">
        <xs:sequence>
            <xs:element name="region" type="RegionType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <!-- Тип за регион -->
    <xs:complexType name="RegionType">
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>
    
    <!-- Тип за колекция от области -->
    <xs:complexType name="AreasType">
        <xs:sequence>
            <xs:element name="area" type="AreaType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <!-- Тип за област -->
    <xs:complexType name="AreaType">
        <xs:sequence>
            <xs:element name="name" type="xs:string">
                <xs:annotation>
                    <xs:documentation>Име на областта</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="regionRef" type="xs:IDREF" use="required"/>
    </xs:complexType>
    
    <!-- Тип за колекция от крепости -->
    <xs:complexType name="FortressesType">
        <xs:sequence>
            <xs:element name="fortress" type="FortressType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <!-- Тип за крепост -->
    <xs:complexType name="FortressType">
        <xs:sequence>
            <xs:element name="name" type="xs:string">
                <xs:annotation>
                    <xs:documentation>Име на крепостта</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="type" type="FortressTypeEnum">
                <xs:annotation>
                    <xs:documentation>Тип на крепостта според произход</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="subtype" type="xs:string">
                <xs:annotation>
                    <xs:documentation>Подтип/категория на крепостта</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="location" type="LocationType"/>
            <xs:element name="period" type="PeriodType"/>
            <xs:element name="preservation-status" type="PreservationStatusEnum"/>
            <xs:element name="description" type="xs:string">
                <xs:annotation>
                    <xs:documentation>Подробно описание на крепостта</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="features" type="FeaturesType"/>
            <xs:element name="visitor-info" type="VisitorInfoType"/>
            <xs:element name="image" type="xs:string">
                <xs:annotation>
                    <xs:documentation>XML Entity за изображение</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required"/>
    </xs:complexType>
    
    <!-- Изброен тип за видове крепости -->
    <xs:simpleType name="FortressTypeEnum">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Българска"/>
            <xs:enumeration value="Римска"/>
            <xs:enumeration value="Византийска"/>
            <xs:enumeration value="Тракийска"/>
            <xs:enumeration value="Османска"/>
        </xs:restriction>
    </xs:simpleType>
    
    <!-- Изброен тип за състояние на запазеност -->
    <xs:simpleType name="PreservationStatusEnum">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Отлично запазена"/>
            <xs:enumeration value="Добре запазена"/>
            <xs:enumeration value="Частично запазена"/>
            <xs:enumeration value="Частично възстановена"/>
            <xs:enumeration value="Археологически останки"/>
            <xs:enumeration value="Археологически обект"/>
        </xs:restriction>
    </xs:simpleType>
    
    <!-- Тип за местоположение -->
    <xs:complexType name="LocationType">
        <xs:sequence>
            <xs:element name="areaRef" type="xs:IDREF">
                <xs:annotation>
                    <xs:documentation>Референция към област</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="city" type="xs:string"/>
            <xs:element name="coordinates" type="CoordinatesType" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    
    <!-- Тип за координати -->
    <xs:complexType name="CoordinatesType">
        <xs:sequence>
            <xs:element name="latitude">
                <xs:simpleType>
                    <xs:restriction base="xs:decimal">
                        <xs:minInclusive value="41.0"/>
                        <xs:maxInclusive value="44.5"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="longitude">
                <xs:simpleType>
                    <xs:restriction base="xs:decimal">
                        <xs:minInclusive value="22.0"/>
                        <xs:maxInclusive value="28.5"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    
    <!-- Тип за исторически период -->
    <xs:complexType name="PeriodType">
        <xs:sequence>
            <xs:element name="built-era" type="xs:string">
                <xs:annotation>
                    <xs:documentation>Епоха на построяване</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="main-use" type="xs:string">
                <xs:annotation>
                    <xs:documentation>Период на основно използване</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    
    <!-- Тип за характеристики -->
    <xs:complexType name="FeaturesType">
        <xs:sequence>
            <xs:element name="feature" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <!-- Тип за информация за посетители -->
    <xs:complexType name="VisitorInfoType">
        <xs:sequence>
            <xs:element name="entrance-fee" type="EntranceFeeType"/>
            <xs:element name="working-hours" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    
    <!-- Тип за входна такса -->
    <xs:complexType name="EntranceFeeType">
        <xs:sequence>
            <xs:element name="amount" type="AmountType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <!-- Тип за сума -->
    <xs:complexType name="AmountType">
        <xs:simpleContent>
            <xs:extension base="xs:decimal">
                <xs:attribute name="currency" type="CurrencyEnum" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    
    <!-- Изброен тип за валути -->
    <xs:simpleType name="CurrencyEnum">
        <xs:restriction base="xs:string">
            <xs:enumeration value="BGN"/>
            <xs:enumeration value="EUR"/>
            <xs:enumeration value="USD"/>
        </xs:restriction>
    </xs:simpleType>
    
</xs:schema>

=== gabriela-n/XML2025_project_37_8MI0600303_855305/fortresses.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="fortresses.xsl"?>

<catalog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="fortresses.xsd">
    
    <!-- Региони -->
    <regions>
        <region id="BG31" name="Северозападен регион"/>
        <region id="BG32" name="Северен централен регион"/>
        <region id="BG33" name="Североизточен регион"/>
        <region id="BG34" name="Югоизточен регион"/>
        <region id="BG41" name="Югозападен регион"/>
        <region id="BG42" name="Южен централен регион"/>
    </regions>

    <!-- Области -->
    <areas>
        <area id="BG311" regionRef="BG31"><name>Видин</name></area>
        <area id="BG312" regionRef="BG31"><name>Монтана</name></area>
        <area id="BG313" regionRef="BG31"><name>Враца</name></area>
        <area id="BG314" regionRef="BG31"><name>Плевен</name></area>
        <area id="BG315" regionRef="BG31"><name>Ловеч</name></area>
        <area id="BG321" regionRef="BG32"><name>Велико Търново</name></area>
        <area id="BG322" regionRef="BG32"><name>Габрово</name></area>
        <area id="BG323" regionRef="BG32"><name>Русе</name></area>
        <area id="BG324" regionRef="BG32"><name>Разград</name></area>
        <area id="BG325" regionRef="BG32"><name>Силистра</name></area>
        <area id="BG331" regionRef="BG33"><name>Варна</name></area>
        <area id="BG332" regionRef="BG33"><name>Добрич</name></area>
        <area id="BG333" regionRef="BG33"><name>Шумен</name></area>
        <area id="BG334" regionRef="BG33"><name>Търговище</name></area>
        <area id="BG341" regionRef="BG34"><name>Бургас</name></area>
        <area id="BG342" regionRef="BG34"><name>Сливен</name></area>
        <area id="BG343" regionRef="BG34"><name>Ямбол</name></area>
        <area id="BG344" regionRef="BG34"><name>Стара Загора</name></area>
        <area id="BG411" regionRef="BG41"><name>София-град</name></area>
        <area id="BG412" regionRef="BG41"><name>Софийска област</name></area>
        <area id="BG413" regionRef="BG41"><name>Благоевград</name></area>
        <area id="BG414" regionRef="BG41"><name>Перник</name></area>
        <area id="BG415" regionRef="BG41"><name>Кюстендил</name></area>
        <area id="BG421" regionRef="BG42"><name>Пловдив</name></area>
        <area id="BG422" regionRef="BG42"><name>Хасково</name></area>
        <area id="BG423" regionRef="BG42"><name>Пазарджик</name></area>
        <area id="BG424" regionRef="BG42"><name>Смолян</name></area>
        <area id="BG425" regionRef="BG42"><name>Кърджали</name></area>
    </areas>
    
    <!-- Каталог на крепости -->
    <fortresses>
        <!-- Царевец -->
        <fortress id="f001">
            <name>Царевец</name>
            <type>Българска</type>
            <subtype>Царска крепост</subtype>
            <location>
                <areaRef>BG321</areaRef>
                <city>Велико Търново</city>
                <region>Северен централен регион</region>
                <coordinates>
                    <latitude>43.0814</latitude>
                    <longitude>25.6519</longitude>
                </coordinates>
            </location>
            <period>
                <built-era>Византийска епоха (V-VII век)</built-era>
                <main-use>Второ българско царство (XII-XIV век)</main-use>
            </period>
            <preservation-status>Частично възстановена</preservation-status>
            <description>
                Царевец е средновековна крепост в Велико Търново, столица на Второто българско царство. Крепостта се намира на едноименния хълм и е била резиденция на българските царе и патриарси. Запазени са крепостните стени, порти и патриаршеската църква. Днес е музей под открито небе и символ на българската история.
            </description>
            <features>
                <feature>Патриаршеска църква</feature>
                <feature>Царски дворец</feature>
                <feature>Крепостни стени с височина до 10 метра</feature>
                <feature>Балдуинова кула</feature>
            </features>
            <visitor-info>
                <entrance-fee>
                    <amount currency="BGN">6.00</amount>
                    <amount currency="EUR">3.07</amount>
                </entrance-fee>
                <working-hours>09:00-18:00</working-hours>
            </visitor-info>
            <image>tsarevets.jpg</image>
        </fortress>
        
        <!-- Баба Вида -->
        <fortress id="f002">
            <name>Баба Вида</name>
            <type>Българска</type>
            <subtype>Дунавска крепост</subtype>
            <location>
                <areaRef>BG311</areaRef>
                <city>Видин</city>
                <region>Северозападен регион</region>
                <coordinates>
                    <latitude>43.9909</latitude>
                    <longitude>22.8711</longitude>
                </coordinates>
            </location>
            <period>
                <built-era>X-XIV век</built-era>
                <main-use>Средновековна България</main-use>
            </period>
            <preservation-status>Отлично запазена</preservation-status>
            <description>
                Баба Вида е единствената напълно запазена средновековна крепост в България. Разположена на брега на река Дунав във Видин, крепостта е построена върху основите на римската крепост Бононя. Името й произлиза от легендата за владетелката Вида. Крепостта е с два концентрични реда крепостни стени и четири кули.
            </description>
            <features>
                <feature>Два реда крепостни стени</feature>
                <feature>Четири бойни кули</feature>
                <feature>Водна защита от Дунав</feature>
                <feature>Средновековен мост</feature>
            </features>
            <visitor-info>
                <entrance-fee>
                    <amount currency="BGN">4.00</amount>
                    <amount currency="EUR">2.05</amount>
                </entrance-fee>
                <working-hours>09:00-17:00</working-hours>
            </visitor-info>
            <image>baba-vida.jpg</image>
        </fortress>
        
        <!-- Асенова крепост -->
        <fortress id="f003">
            <name>Асенова крепост</name>
            <type>Византийска</type>
            <subtype>Планинска крепост</subtype>
            <location>
                <areaRef>BG421</areaRef>
                <city>Асеновград</city>
                <region>Южен централен регион</region>
                <coordinates>
                    <latitude>41.9831</latitude>
                    <longitude>24.8731</longitude>
                </coordinates>
            </location>
            <period>
                <built-era>Византийска епоха (XI век)</built-era>
                <main-use>Средновековна България (XIII-XIV век)</main-use>
            </period>
            <preservation-status>Частично запазена</preservation-status>
            <description>
                Асенова крепост е средновековна крепост в Родопите, известна още като Асеновата крепост. Разположена е на скалист рид край Асеновград. Възстановена е от цар Иван Асен II през XIII век. Най-забележителен е запазената църква "Света Богородица Петричка" с ценни стенописи от XIII-XIV век.
            </description>
            <features>
                <feature>Църква "Света Богородица Петричка"</feature>
                <feature>Средновековни стенописи</feature>
                <feature>Крепостни кули</feature>
                <feature>Скално укрепление</feature>
            </features>
            <visitor-info>
                <entrance-fee>
                    <amount currency="BGN">3.00</amount>
                    <amount currency="EUR">1.53</amount>
                </entrance-fee>
                <working-hours>08:30-17:30</working-hours>
            </visitor-info>
            <image>asenova.jpg</image>
        </fortress>
        
        <!-- Белоградчишка крепост -->
        <fortress id="f004">
            <name>Белоградчишка крепост</name>
            <type>Римска</type>
            <subtype>Скална крепост</subtype>
            <location>
                <areaRef>BG311</areaRef>
                <city>Белоградчик</city>
                <region>Северозападен регион</region>
                <coordinates>
                    <latitude>43.6272</latitude>
                    <longitude>22.6850</longitude>
                </coordinates>
            </location>
            <period>
                <built-era>Римска епоха (I-III век)</built-era>
                <main-use>Средновековна България (XIV век)</main-use>
            </period>
            <preservation-status>Добре запазена</preservation-status>
            <description>
                Белоградчишката крепост е разположена сред Белоградчишките скали и е един от най-добре запазените паметници на крепостното строителство в България. Построена е върху римска основа и е развивана през византийската и българската епохи. Крепостта е естествено защитена от скалните образувания.
            </description>
            <features>
                <feature>Три крепостни двора</feature>
                <feature>Естествена скална защита</feature>
                <feature>Римски основи</feature>
                <feature>Наблюдателни кули</feature>
            </features>
            <visitor-info>
                <entrance-fee>
                    <amount currency="BGN">5.00</amount>
                    <amount currency="EUR">2.56</amount>
                </entrance-fee>
                <working-hours>09:00-18:00</working-hours>
            </visitor-info>
            <image>belogradchick.jpg</image>
        </fortress>
